version: "3.7"

networks: 
    laravel-9:
        driver: bridge

services:
    # image project
    app:
        container_name: leaseweb
        build:
            context: .
            dockerfile: Dockerfile
        image: evandro/leaseweb
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - laravel-9
    
    # nginx
    nginx:
        container_name: evandro-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-9
